version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistics

  web:
    build: .
    expose:
    - 5000
    ports:
    - '5000:5000'
    depends_on:
    - db